# Generated by Django 4.1.4 on 2023-03-21 14:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreenpayPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(default='NDI1Njg1Njg3NTlDQkZBQkEzMzg3NDhFMTY0MkIzN0I1MTMzRjRBQjcwNkE4NDE5MTYzRjUwNDg4RkNDMUMwMEZCRkMwNEU3MTA3MDg4RDE4QzEzMzNGRUFGMjdCNERBQTZDQzM4RTA5Q0RDMjUyNTkwN0Y2NTYxOUVGOTlBOTE=', max_length=255, verbose_name='Secret key')),
                ('public', models.CharField(default='MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCtHv7xBNK8g4IG88gdaYnPA9BjaWqJVKTNJW+5TGWaq2ApO0sibHfy9feK30daK2lqM6vd6gjEADjiblrSAQ5tPc6WRcmN0v2dImpvvoHucoAyBkgtLkJjWpVnyt8sXaDRXU0jkFb+89PVewMZUWBM5eKHv2Dbs2ZSDP3gMadoNwIDAQAB', max_length=255, verbose_name='Public key')),
                ('merchantId', models.CharField(default='6e25a52c-399d-4cc8-b088-b4a8f59f9d82', max_length=255, verbose_name='Merchant ID')),
                ('terminal_id', models.CharField(default='ticketcrushh-f77c-BNCR-USD', max_length=255, verbose_name='Terminal ID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GTQ', 'GTQ'), ('HNL', 'HNL'), ('NIO', 'NIO'), ('CRC', 'CRC'), ('PAB', 'PAB'), ('DOP', 'DOP')], default='USD', max_length=10, verbose_name='Status')),
                ('url', models.CharField(blank=True, default='https://sandbox-merchant.greenpay.me/', max_length=255, null=True, verbose_name='Payment URL')),
            ],
            options={
                'verbose_name': 'greenpay',
                'verbose_name_plural': 'greenpay',
            },
        ),
        migrations.CreateModel(
            name='PagaditoPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsk', models.CharField(max_length=255, verbose_name='WSK')),
                ('uid', models.CharField(max_length=255, verbose_name='UID')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GTQ', 'GTQ'), ('HNL', 'HNL'), ('NIO', 'NIO'), ('CRC', 'CRC'), ('PAB', 'PAB'), ('DOP', 'DOP')], default='USD', max_length=10, verbose_name='Status')),
                ('url', models.CharField(max_length=255, verbose_name='Connect URL')),
                ('redirect_url', models.CharField(max_length=255, verbose_name='Redirect URL')),
            ],
            options={
                'verbose_name': 'pagadito',
                'verbose_name_plural': 'pagadito',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('front_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='FRONT_KEY')),
                ('site_title', models.CharField(blank=True, max_length=200, verbose_name='Site title')),
            ],
            options={
                'verbose_name': 'settings: back',
                'verbose_name_plural': 'settings: back',
            },
        ),
    ]
