# Generated by Django 4.1.4 on 2023-04-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='front_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Front URL'),
        ),
        migrations.AddField(
            model_name='preference',
            name='google_redirect_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Google url'),
        ),
    ]
