# Generated by Django 4.1.4 on 2023-06-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_testblock_delete_greenpaypreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagaditoPreference',
        ),
    ]
