version: '3'

services:

  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      sh -c "gunicorn -w 4 -b 0.0.0.0:8000 settings.wsgi:application &
             daphne -b 0.0.0.0 -p 8001 settings.asgi:application"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: 5432
      CHANNEL_HOSTS: redis
      CHANNEL_PORT: 6379
      GIT_ACTION: "TRUE"
      USE_S3: "FALSE"
      AWS_ACCESS_KEY_ID: CHANGE_ME
      AWS_SECRET_ACCESS_KEY: CHANGE_ME
      AWS_STORAGE_BUCKET_NAME: CHANGE_ME
      AWS_LOCATION: CHANGE_ME
    depends_on:
      - db
      - migrate

  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always
    container_name: postgres

  migrate:
    build: .
    command: sh -c "python manage.py migrate --noinput & python manage.py createmysuperuser"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    container_name: migrations


volumes:
  postgres_data:
