# Generated by Django 4.1.4 on 2023-03-21 14:34

import applications.core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LetterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('image_logo', models.ImageField(blank=True, null=True, upload_to=applications.core.models.PathAndRename('sales/letter/images'), verbose_name='Logo TicketCrush')),
                ('image_ticket_left', models.ImageField(blank=True, null=True, upload_to=applications.core.models.PathAndRename('sales/letter/images'), verbose_name='Tickets left')),
                ('image_ticket_right', models.ImageField(blank=True, null=True, upload_to=applications.core.models.PathAndRename('sales/letter/images'), verbose_name='Tickets right')),
                ('image_youtube_logo', models.ImageField(blank=True, null=True, upload_to=applications.core.models.PathAndRename('sales/letter/images'), verbose_name='Youtube')),
            ],
            options={
                'verbose_name': 'LetterImage',
                'verbose_name_plural': 'LetterImage',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('condition', models.CharField(choices=[('open', 'open'), ('read', 'read')], default='open', max_length=50, verbose_name='Condition')),
                ('user_uuid', models.CharField(max_length=255, null=True, verbose_name='USER Unique id')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique id')),
                ('status', models.CharField(choices=[('purchase', 'purchase'), ('waiting', 'waiting'), ('blocked', 'blocked'), ('payed', 'payed')], default='waiting', max_length=10, verbose_name='Status')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Phonenumber')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Admin comment')),
                ('payment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link payment')),
                ('token_trans', models.CharField(blank=True, max_length=255, null=True, verbose_name='token_trans')),
                ('redirect_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='redirect_url')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created'],
            },
        ),
    ]
