# Generated by Django 4.1.4 on 2023-03-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='add_hash',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Add hash'),
        ),
    ]
