# Generated by Django 4.1.4 on 2023-03-29 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_order_add_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTokenService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='published', max_length=50, verbose_name='Status')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token')),
                ('last_digits', models.CharField(max_length=4, verbose_name='Last digits')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Service payment token',
                'verbose_name_plural': 'Service payment token',
            },
        ),
    ]
