# Generated by Django 4.1.4 on 2023-06-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_paymenttokenservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255, verbose_name='ACCESS TOKEN')),
            ],
            options={
                'verbose_name': 'Mercado Pago',
                'verbose_name_plural': 'Mercado Pago',
            },
        ),
    ]
