# Generated by Django 4.1.4 on 2023-06-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_mercadopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadopago',
            name='public_key',
            field=models.CharField(default='set_your', max_length=255, verbose_name='PUBLIC KEY'),
        ),
        migrations.AlterField(
            model_name='mercadopago',
            name='access_token',
            field=models.CharField(default='set_your', max_length=255, verbose_name='ACCESS TOKEN'),
        ),
    ]
