# Generated by Django 4.1 on 2022-08-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='url',
            field=models.URLField(default=False),
        ),
    ]
