# Generated by Django 4.1.1 on 2022-09-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.BooleanField(default=True)),
            ],
        ),
    ]
