version: "3.8"

services:
  api_general:
    container_name: api_general
    hostname: general
    build: .
    command: bash -c "alembic upgrade head & python main.py"
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      - db
    networks:
      - network
    env_file:
      - .env
  db:
    image: postgres
    container_name: db
    volumes:
      - .:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    networks:
      - network
  nginx:
    build: ./nginx
    ports:
      - 80:80
    networks:
      - network

networks:
  network:
    name: network

